version: '3.8'

services:

  basic-info:
    image: basic-info-node:10
    ports:
      - "80:8080"
      - "8080:8080"
    expose: []
    networks:
      - frontend
    volumes: []
    depends_on: []

    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: 32M
        reservations:
          cpus: '0.125'
          memory: 8M
    env_file: []
    environment: []
    secrets: []


networks:
  frontend: